Dev/ar/redev
OVHJabberBots/jabberbot pull request #26
Opened 2018-01-31 19:19 UTC by AdrienR

2018-01-31 19:44 UTC, jlejeune commented on .gitignore
> +*pyc
*.pyc instead of *pyc no?

2018-02-01 08:16 UTC, arnaudmorin requested changes
haricot

2018-02-01 08:16 UTC, arnaudmorin commented on OVHJabberBot/commands/baguette.py
>      results = [user.name for user in notifs if user not in [order.name for order in orders] and user not in non_list]
ta un haricot ici

2018-02-03 12:58 UTC, arnaudmorin approved these changes
haricot proof

2018-02-03 12:58 UTC, merged